@startuml
title 20. UML - Decorator trong Voucher/Giảm giá

skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam roundCorner 12
skinparam class {
  BackgroundColor #FFFFFF
  BorderColor #000000
  ArrowColor #000000
  FontColor #000000
  FontSize 14
  FontStyle bold
}

class CheckoutFacade {
}

class BaseCartPrice <<Component>> {
}

class PercentDiscountDecorator <<Decorator>> {
}

class AmountDiscountDecorator <<Decorator>> {
}

class FreeshipDecorator <<Decorator>> {
}

CheckoutFacade --> BaseCartPrice
CheckoutFacade --> PercentDiscountDecorator
CheckoutFacade --> AmountDiscountDecorator
CheckoutFacade --> FreeshipDecorator

@enduml
